# syntax = docker/dockerfile:1.11-labs

FROM input AS typos
ARG rust_toolchain="nightly"
ARG RUSTUP_HOME
ARG CARGO_HOME
ARG typos_args=""
ARG sched_policy="--rr"
ARG sched_prio=1

WORKDIR /usr/src/tuwunel
ENV sched_policy=${sched_policy}
ENV sched_prio=${sched_prio}
RUN <<EOF
    set -eux
    rustup run ${rust_toolchain} sched_wrap.sh \
        typos \
            --color always \
            --exclude docker \
            --exclude nix \
            --exclude RELEASE.md \
            --exclude 'tests/complement/*.jsonl' \
            --exclude 'tests/playwright/known-failures.txt' \
            --exclude 'docs/development/compliance/msc.md' \
            --exclude 'docs/development/testing/performance.md' \
            ${typos_args}
EOF
