# syntax = docker/dockerfile:1.11-labs

FROM input AS fmt
ARG sys_target
ARG rust_toolchain="nightly"
ARG RUSTUP_HOME
ARG CARGO_HOME
ARG fmt_args=""

WORKDIR /usr/src/tuwunel
RUN \
--mount=type=cache,dst=${RUSTUP_HOME},sharing=locked \
--mount=type=cache,dst=${CARGO_HOME},sharing=locked \
<<EOF
    set -eux
    rustup run ${rust_toolchain} \
        cargo fmt \
            --all \
            --check \
            --manifest-path Cargo.toml \
            ${fmt_args}
EOF
